# Generated by Django 5.0.6 on 2024-06-09 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectSummary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectsummary',
            options={'verbose_name': 'Project Summary', 'verbose_name_plural': 'Project Summaries'},
        ),
    ]
