# Generated by Django 5.0.6 on 2024-06-10 12:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_alter_membership_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='facilities',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
