# Generated by Django 5.0.6 on 2024-06-12 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_membership_facilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipFacilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilities', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Membership Facilities',
                'verbose_name_plural': 'Memberships Facilities',
            },
        ),
        migrations.RemoveField(
            model_name='membership',
            name='facilities',
        ),
    ]
