# Generated by Django 5.0.6 on 2024-06-12 10:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_membershipfacilities_remove_membership_facilities'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MembershipFacilities',
        ),
        migrations.AddField(
            model_name='membership',
            name='facilities',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
