# Generated by Django 5.0.6 on 2024-06-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='teammember/')),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('facebook_link', models.URLField(blank=True, max_length=500, null=True)),
                ('twitter_link', models.URLField(blank=True, max_length=500, null=True)),
                ('instagram_link', models.URLField(blank=True, max_length=500, null=True)),
                ('linkedin_link', models.URLField(blank=True, max_length=500, null=True)),
                ('dribble_link', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
            },
        ),
    ]
