# Generated by Django 5.0.6 on 2024-06-09 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0001_initial'),
        ('teammember', '0002_aboutus_alter_teammember_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='position',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='position.position'),
            preserve_default=False,
        ),
    ]
