# Generated by Django 5.0.6 on 2024-06-09 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teammember', '0003_teammember_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='position',
        ),
    ]
