# Generated by Django 5.0.6 on 2024-06-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammember', '0005_teammember_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeoAboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_one', models.CharField(max_length=500, verbose_name='Title One')),
                ('title_two', models.CharField(max_length=500, verbose_name='Title Two')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_us/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'CEO About Us',
                'verbose_name_plural': 'CEO About Us',
            },
        ),
        migrations.CreateModel(
            name='VideoAboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_one', models.CharField(max_length=500, verbose_name='Title One')),
                ('title_two', models.CharField(max_length=500, verbose_name='Title Two')),
                ('description', models.TextField(verbose_name='Description')),
                ('video', models.FileField(blank=True, null=True, upload_to='about_us/', verbose_name='Video')),
            ],
            options={
                'verbose_name': 'Video About Us',
                'verbose_name_plural': 'Video About Us',
            },
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='video',
        ),
    ]
