# Generated by Django 5.0.6 on 2024-06-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammember', '0006_ceoaboutus_videoaboutus_remove_aboutus_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ceoaboutus',
            name='description',
        ),
        migrations.RemoveField(
            model_name='videoaboutus',
            name='description',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_one',
            field=models.TextField(blank=True, null=True, verbose_name='Description_one'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_two',
            field=models.TextField(blank=True, null=True, verbose_name='Description_two'),
        ),
        migrations.AddField(
            model_name='ceoaboutus',
            name='description_one',
            field=models.TextField(blank=True, null=True, verbose_name='Description_one'),
        ),
        migrations.AddField(
            model_name='ceoaboutus',
            name='description_two',
            field=models.TextField(blank=True, null=True, verbose_name='Description_two'),
        ),
        migrations.AddField(
            model_name='videoaboutus',
            name='description_one',
            field=models.TextField(blank=True, null=True, verbose_name='Description_one'),
        ),
        migrations.AddField(
            model_name='videoaboutus',
            name='description_two',
            field=models.TextField(blank=True, null=True, verbose_name='Description_two'),
        ),
    ]
