# Generated by Django 5.0.6 on 2024-06-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammember', '0007_remove_aboutus_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoaboutus',
            name='video',
        ),
        migrations.AddField(
            model_name='videoaboutus',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Video URL'),
        ),
    ]
