# Generated by Django 5.0.6 on 2024-06-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('amount', models.IntegerField()),
                ('image', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Company Summary',
                'verbose_name_plural': 'Company Summaries',
            },
        ),
    ]
