# Generated by Django 5.0.6 on 2024-06-04 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companysummary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companysummary',
            old_name='image',
            new_name='icon',
        ),
    ]
