# Generated by Django 5.0.6 on 2024-06-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactinfo', '0002_usercontact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'Contact Information', 'verbose_name_plural': 'Contact Information'},
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='facebook_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Facebook Profile'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='instagram_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Instagram Profile'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='linkedin_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='LinkedIn Profile'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone_number_one',
            field=models.CharField(max_length=15, verbose_name='Primary Phone Number'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone_number_two',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Secondary Phone Number'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='youtube_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='YouTube Channel'),
        ),
        migrations.AlterField(
            model_name='usercontact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='usercontact',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='usercontact',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='usercontact',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='usercontact',
            name='subject',
            field=models.CharField(max_length=500, verbose_name='Subject'),
        ),
    ]
