# Generated by Django 5.0.6 on 2024-06-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactinfo', '0003_alter_contactinfo_options_alter_contactinfo_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='facebook_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='instagram_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='linkedin_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone_number_one',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone_number_two',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='youtube_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='usercontact',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='usercontact',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usercontact',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='usercontact',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='usercontact',
            name='subject',
            field=models.CharField(max_length=500),
        ),
    ]
