# Generated by Django 5.0.6 on 2024-06-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactinfo', '0004_alter_contactinfo_address_alter_contactinfo_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='phone_number_one',
            field=models.CharField(max_length=17),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone_number_two',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='usercontact',
            name='phone_number',
            field=models.CharField(max_length=17),
        ),
    ]
