# Generated by Django 5.0.6 on 2024-06-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=500)),
                ('project_code', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('brochure_pdf', models.FileField(upload_to='brochures/')),
            ],
            options={
                'verbose_name': 'Company Summary',
                'verbose_name_plural': 'Company Summaries',
            },
        ),
    ]
