# Generated by Django 5.0.6 on 2024-06-09 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_description_alter_project_project_code'),
        ('teammember', '0005_teammember_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teammember.teammember'),
            preserve_default=False,
        ),
    ]
