# Generated by Django 5.0.6 on 2024-06-11 18:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_agent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='description_one',
        ),
        migrations.AddField(
            model_name='project',
            name='description_two',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
