# Generated by Django 5.0.6 on 2024-06-12 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_project_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description_one',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description_two',
        ),
    ]
