# Generated by Django 5.0.6 on 2024-06-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='investment_Three/')),
            ],
            options={
                'verbose_name': 'Investment Three',
                'verbose_name_plural': 'Investments Three',
            },
        ),
        migrations.CreateModel(
            name='InvestmentTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='investment_Two/')),
            ],
            options={
                'verbose_name': 'Investment Two',
                'verbose_name_plural': 'Investments Two',
            },
        ),
        migrations.AlterField(
            model_name='investment',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='investment/'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
