# Generated by Django 5.0.6 on 2024-06-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0002_investmentthree_investmenttwo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptionInvestmentOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Investment Description One',
                'verbose_name_plural': 'Investment Description One',
            },
        ),
        migrations.CreateModel(
            name='DescriptionInvestmentThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Investment Description Three',
                'verbose_name_plural': 'Investment Description Three',
            },
        ),
        migrations.CreateModel(
            name='DescriptionInvestmentTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Investment Description Two',
                'verbose_name_plural': 'Investment Description Two',
            },
        ),
        migrations.RemoveField(
            model_name='investment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='investmentthree',
            name='description',
        ),
        migrations.RemoveField(
            model_name='investmenttwo',
            name='description',
        ),
    ]
