# Generated by Django 5.0.6 on 2024-06-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0004_manualtest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DescriptionInvestmentOne',
        ),
        migrations.DeleteModel(
            name='DescriptionInvestmentThree',
        ),
        migrations.DeleteModel(
            name='DescriptionInvestmentTwo',
        ),
        migrations.AddField(
            model_name='investment',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investmentthree',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='investmenttwo',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
