# Generated by Django 5.0.6 on 2024-06-12 08:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0005_delete_descriptioninvestmentone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='description',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='investmentthree',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='investmenttwo',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
