# Generated by Django 5.0.6 on 2024-06-09 12:10

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0003_project_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProjectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('comment', ckeditor.fields.RichTextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
            options={
                'verbose_name': 'Client Project Request',
                'verbose_name_plural': 'Client Project Requests',
            },
        ),
    ]
