# Generated by Django 5.0.6 on 2024-06-09 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0002_alter_project_description_alter_project_project_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Masterplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masterplan_name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
            options={
                'verbose_name': 'Masterplan',
                'verbose_name_plural': 'Masterplans',
            },
        ),
    ]
