# Generated by Django 5.0.6 on 2024-06-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterplan', '0002_masterplan_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterplan',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='masterplan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Masterplan/'),
        ),
    ]
