# Generated by Django 5.0.6 on 2024-06-11 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterplanDetails', '0001_initial'),
        ('project', '0003_project_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterplandetails',
            name='facilities',
        ),
        migrations.CreateModel(
            name='MasterplanFacilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilities', models.CharField(blank=True, max_length=500, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
            options={
                'verbose_name': 'Masterplan Facilities',
                'verbose_name_plural': 'Masterplan Facilities',
            },
        ),
    ]
