# Generated by Django 5.0.6 on 2024-06-12 09:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterplanDetails', '0002_remove_masterplandetails_facilities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterplandetails',
            name='facilities',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MasterplanFacilities',
        ),
    ]
